language: rust

services:
  - docker

cache:
  - cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - test $TRAVIS_RUST_VERSION != "nightly" || rustup component add rustfmt

script:
  - test $TRAVIS_RUST_VERSION != "nightly" || cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose

after_success:
  - test $TRAVIS_BRANCH = "master" -a $TRAVIS_RUST_VERSION = "stable" &&
    cargo doc &&
    echo '<html><head><meta http-equiv=refresh content=0;url=rspg/index.html /></head></html>' > target/doc/index.html
  - test $TRAVIS_RUST_VERSION = "stable" &&
    docker pull xd009642/tarpaulin &&
    docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin sh -c
    "cargo tarpaulin  --ciserver travis-ci --coveralls $TRAVIS_JOB_ID"

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
