language: rust
rust:
- stable

after_success:
  - cargo doc
  - echo '<html><head><meta http-equiv=refresh content=0;url=simple_parser_generator/index.html /></head></html>' > target/doc/index.html

deploy:
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
