[package]
name = "rspg"
version = "0.0.0"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "0.8"

[dev-dependencies]
lazy_static = "1.3"
log = "0.4"
env_logger = "0.7"
rustyline = "5.0"
