[package]
name = "rspg"
version = "0.0.0"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"

[dependencies]
prettytable-rs = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.4"
log = "0.4"
env_logger = "0.7"
rustyline = "6.2"
