[package]
name = "rspg-macros"
version = "0.0.1"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"
description = "Macros for rspg."
license = "MIT"
homepage = "https://github.com/linyinfeng/rspg"
repository = "https://github.com/linyinfeng/rspg"
keywords = ["parser", "generator", "LR", "grammar"]
categories = ["parsing"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
rspg = { version = "^0.0.1-alpha.1", path = "../rspg" }
syn = { version = "1.0.36", features = ["full", "extra-traits"] }
quote = "1.0.7"
proc-macro2 = "1.0.19"
serde = "1.0.114"
ron = "0.6.0"
