[package]
name = "rspg-macros"
version = "0.0.0"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/linyinfeng/rspg"
repository = "https://github.com/linyinfeng/rspg"
keywords = ["parser", "generator", "LR", "grammar"]
categories = ["parsing"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
rspg = { version = "0.0.0", path = "../rspg" }
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
serde = "1"
ron = "0.6"
