[package]
name = "rspg-examples"
version = "0.0.0"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"
publish = false

[[bin]]
name = "lambda"
path = "src/lambda/main.rs"

[[bin]]
name = "lambda-macros"
path = "src/lambda-macros/main.rs"

[[bin]]
name = "simple-calculator"
path = "src/simple-calculator/main.rs"

[dependencies]
rspg = { path = "../rspg" }
rspg-macros = { path = "../rspg-macros" }
lazy_static = "*"
log = "*"
env_logger = "*"
rustyline = "*"
ron = "*"
