
name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        rust: [stable, beta]
        experimental: [false]
        include:
          - rust: nightly
            experimental: true

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: set grcov environment variables
        run: |
          echo '::set-env CARGO_INCREMENTAL=0'
          echo '::set-env RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"'
          echo '::set-env RUSTDOCFLAGS="-Cpanic=abort"'
        if: ${{ matrix.rust == 'nightly' }}

      - uses: actions-rs/cargo@master
        with:
          command: build
          args: --tests --examples

      - uses: actions-rs/cargo@master
        with:
          command: test
          args: --workspace

      - uses: actions-rs/cargo@master
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@master
        with:
          command: clippy
          args: -- -D warnings

      - id: coverage
        uses: actions-rs/grcov@master
        if: ${{ matrix.rust == 'nightly' }}

      - uses: codecov/codecov-action@master
        with:
          file: ${{ steps.coverage.outputs.report }}
        if: ${{ matrix.rust == 'nightly' }}
