
name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        rust: [stable, beta]
        experimental: [false]
        include:
          - rust: nightly
            experimental: true

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install toolchain
        uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Check format
        uses: actions-rs/cargo@master
        with:
          command: fmt
          args: -- --check

      - name: Build
        uses: actions-rs/cargo@master
        with:
          command: build
          args: --all-targets

      - name: Test
        uses: actions-rs/cargo@master
        with:
          command: test
          args: --all-targets

      - name: Clippy
        uses: actions-rs/cargo@master
        with:
          command: clippy
          args: --all-targets -- -D warnings
